title: Will Marella
description: Data Scientist · Biological Aging · Software
url: "https://will-marella.github.io"
baseurl: "/portfolio"

author:
  name: Will Marella
  email: wm2551@cumc.columbia.edu
  linkedin: https://www.linkedin.com/in/will-marella-3862921a9/
  github: https://github.com/will-marella
  cv: /assets/WillMarella_CV.pdf

markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor
